### ISSUE TITLE
Need Tutorial

### ISSUE THREAD

**Issue by raniaamina** [tscanlin/svgsplit#3]
Hi, i think you need to add step by step how to use this tool in your README.md. 
I've checked and got confuse moment after dragging SVG file :")
Thanks

**Comment by tscanlin** [comment]
When you drag and drop the file it should automatically download a zip with the groups split into svg files. Can you share your svg here so I can help you debug? Also, if there's specific ways to improve the readme please let me know or feel free to open a PR.

**Comment by Lejla94** [comment]
Is there a way or repo to put all svg files in a folder and then split them on another folder.
I want a command line way to use this. Not drag.
Thanks.
I was looking for something like this before i try to implement my own.

**Comment by tscanlin** [comment]
Not that I am aware of. But I'm curious, what is your use case?

**Comment by raniaamina** [comment]
@Lejla94 not sure about what you need, but i also create a tool to works with SVG (especially Inkscape SVG)

https://citramanik.dev-is.my.id
