### ISSUE TITLE
Bug on <g> more than 100

### ISSUE THREAD

**Issue by bambang-ap** [tscanlin/svgsplit#4]
Hi, your project is awesome.

but i found a bug with `<g>` more than 100. Downloader wont open, its blocked in my svg

here is svg file to reproduce https://bit.ly/3ftcL0Z

so, I modified some of your code

please update for the downloader code become 

        const length = Object.keys(zip.files)
        let newZip = []
        let index = -1
        length.forEach((k, i) => {
          if (i % 100 == 0) {
            newZip.push(new JSZip())
            index++
          }
          newZip[index].file(k, zip.files[k].asText())
        })

        newZip.forEach((z, i) => {
          console.log(i)
          location.href = `data:application/zip;base64,${z.generate()}`
        })

Thanks

**Comment by tscanlin** [comment]
Sorry for the delay and thanks for the great suggestion!
I've updated it to include your suggestion in this commit: https://github.com/tscanlin/svgsplit/commit/694ce8e44f4ec0c30052d887cd0fd0bbdac820cc
