### ISSUE TITLE
Redirect about:blank#blocked

### ISSUE THREAD

**Issue by arpa42** [tscanlin/svgsplit#5]
When my file is uploaded, I'm redirected to `about:blank#blocked`

**Comment by tscanlin** [comment]
Hmm, how large is the svg file? Maybe its too big?

Is it possible to share an example of this issue so I can try to troubleshoot as I cannot reproduce this error.

**Comment by arpa42** [comment]
Ah yes I think the file is too big. Its size is 27.3MB.

**Comment by tscanlin** [comment]
Yep, that'd do it. I think it needs to be under 10MB, but let me know if you find out otherwise.
